import type { Skill } from '@/types/portfolio';

export const skills: Skill[] = [
  { name: 'Kotlin', level: 'Advanced', category: 'Mobile', projects: ['Aceneobank', 'Ace Services'], years: 3 },
  { name: 'Java', level: 'Advanced', category: 'Mobile', projects: ['Aceneobank'], years: 4 },
  { name: 'Jetpack Compose', level: 'Advanced', category: 'Mobile', projects: ['Aceneobank'], years: 2 },
  { name: 'Android SDK', level: 'Advanced', category: 'Mobile', projects: ['Aceneobank', 'Ace Services'], years: 3 },
  { name: 'MVVM', level: 'Advanced', category: 'Architecture', projects: ['Aceneobank'], years: 3 },
  { name: 'Clean Architecture', level: 'Advanced', category: 'Architecture', projects: ['Aceneobank'], years: 2 },
  { name: 'Coroutines', level: 'Advanced', category: 'Mobile', projects: ['Aceneobank'], years: 3 },
  { name: 'Flow', level: 'Advanced', category: 'Mobile', projects: ['Aceneobank'], years: 2 },
  { name: 'Hilt', level: 'Intermediate', category: 'Mobile', projects: ['Aceneobank'], years: 2 },
  { name: 'Retrofit', level: 'Advanced', category: 'Mobile', projects: ['Aceneobank', 'Chat App'], years: 3 },
  { name: 'Firebase', level: 'Expert', category: 'Cloud', projects: ['Aceneobank', 'Chat App'], years: 3 },
  { name: 'Room', level: 'Advanced', category: 'Mobile', projects: ['Aceneobank'], years: 2 },
  { name: 'Node.js', level: 'Intermediate', category: 'Backend', projects: ['Admin Panel API'], years: 2 },
  { name: 'Express', level: 'Intermediate', category: 'Backend', projects: ['Admin Panel API'], years: 2 },
  { name: 'PostgreSQL', level: 'Intermediate', category: 'Backend', projects: ['Admin Panel API'], years: 2 },
  { name: 'Redis', level: 'Basic', category: 'Backend', projects: ['Admin Panel API'], years: 1 },
  { name: 'AWS', level: 'Intermediate', category: 'Cloud', projects: ['Admin Panel API'], years: 2 },
  { name: 'Docker', level: 'Intermediate', category: 'DevOps', projects: ['Admin Panel API'], years: 1 },
  { name: 'CI/CD', level: 'Intermediate', category: 'DevOps', projects: ['Aceneobank'], years: 2 },
  { name: 'GitHub Actions', level: 'Intermediate', category: 'DevOps', projects: ['Aceneobank'], years: 2 },
  { name: 'GraphQL', level: 'Basic', category: 'Backend', projects: [], years: 1 },
  { name: 'TypeScript', level: 'Intermediate', category: 'Backend', projects: ['Admin Panel API'], years: 2 },
  { name: 'React', level: 'Intermediate', category: 'Frontend', projects: ['Admin Panel'], years: 2 },
];

export const galaxyConnections: { source: string; target: string }[] = [
  { source: 'Kotlin', target: 'Jetpack Compose' },
  { source: 'Kotlin', target: 'Coroutines' },
  { source: 'Kotlin', target: 'MVVM' },
  { source: 'MVVM', target: 'Clean Architecture' },
  { source: 'Kotlin', target: 'Retrofit' },
  { source: 'Retrofit', target: 'Node.js' },
  { source: 'Node.js', target: 'Express' },
  { source: 'Express', target: 'PostgreSQL' },
  { source: 'Firebase', target: 'Kotlin' },
  { source: 'AWS', target: 'Docker' },
  { source: 'Docker', target: 'CI/CD' },
  { source: 'CI/CD', target: 'GitHub Actions' },
  { source: 'Hilt', target: 'Kotlin' },
  { source: 'Room', target: 'Kotlin' },
  { source: 'TypeScript', target: 'Node.js' },
  { source: 'React', target: 'TypeScript' },
];
